### PR TITLE
Filled in form for submission

### PR DESCRIPTION
**Pull request by code-warrior**

### CODE REVIEW

**Comment by code-warrior** [comment]
This pull request contains the updated README from the `master` branch and the PDF form, complete will populated form fields for submission.

**Comment by code-warrior** [comment]
@sbambrick1217 : Please review.

**Comment by sbambrick1217** [comment]
@code-warrior It doesn't matter that the font sizes are slightly different for certain questions, correct? Some of them change when clicked on.

Other than that, this looks perfect.

**Comment by code-warrior** [comment]
The font sizes differ because there is more content in some form fields, so the text had to be made smaller to fit. You’ll also note that the content is crowded, regardless of font size. This is because the line-spacing cannot be modified. Let’s leave it, as it’s not a deal breaker.

**Comment by sbambrick1217** [comment]
Fine with me... thumbs up! Let’s send it off.

On Dec 27, 2019, at 12:26 PM, Roy Vanegas <notifications@github.com> wrote:

﻿

The font sizes differ because there is more content in some form fields, so
the text had to be made smaller to fit. You’ll also note that the content
is crowded, regardless of font size. This is because the line-spacing
cannot be modified. Let’s leave it, as it’s not a deal breaker.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/code-warrior/uis-proposal/pull/11?email_source=notifications&email_token=ALSCOI6RIMNHBQA5NUEXRU3Q2Y3GBA5CNFSM4J76OFU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHXQDOY#issuecomment-569311675>,
or unsubscribe

**Pull request merged**
